CREATE TABLE IF NOT EXISTS BOOK_DETAILS  (
    SERIAL_NO  BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOOK_NAME  VARCHAR(255) NOT NULL,
    AUTHOR_NAME  VARCHAR(255) NOT NULL,
    PUBLISH_YEAR  BIGINT NOT NULL,
    QUANTITY INT
);

INSERT INTO BOOK_DETAILS (SERIAL_NO, BOOK_NAME, AUTHOR_NAME, PUBLISH_YEAR, QUANTITY)
VALUES (1, 'The Great Gatsby', 'F. Scott Fitzgerald', 1925, 10);

INSERT INTO BOOK_DETAILS (SERIAL_NO, BOOK_NAME, AUTHOR_NAME, PUBLISH_YEAR, QUANTITY)
VALUES (2, 'The Great', 'F. Scott Fitzgerald', 1925, 10);

INSERT INTO BOOK_DETAILS (SERIAL_NO, BOOK_NAME, AUTHOR_NAME, PUBLISH_YEAR, QUANTITY)
VALUES (3, 'The Gatsby', 'F. Scott Fitzgerald', 1925, 10);

INSERT INTO BOOK_DETAILS (SERIAL_NO, BOOK_NAME, AUTHOR_NAME, PUBLISH_YEAR, QUANTITY)
VALUES (4, 'To Kill a Mockingbird', 'Harper Lee', 1960, 5);

INSERT INTO BOOK_DETAILS (SERIAL_NO, BOOK_NAME, AUTHOR_NAME, PUBLISH_YEAR, QUANTITY)
VALUES (5, '1984', 'George Orwell', 1949, 15);

--INSERT INTO bookDetails (serialNo, bookName, authorName, publishYear, quantity) VALUES (1, "Corporate","Vijai Sundaram", 2018, 100);
--INSERT INTO bookDetails(serialNo, bookName, authorName, publishYear, quantity) VALUES (2, "True Love","Viju Mamu", 2024, 1);